# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

includes:
  vendor: ./vendor

vars:
  CLI_PROJECT_ROOT: "{{.TASKFILE_DIR}}/cmd/cli"
  APP_PROJECT_ROOT: "{{.TASKFILE_DIR}}/cmd/app"
  BUILD_DIR: "{{.TASKFILE_DIR}}/build"

tasks:
  cli:
    desc: Run codefolio CLI
    cmds:
      - go run {{.CLI_PROJECT_ROOT}}
    silent: true
    interactive: true

  app:
    desc: Run Codefolio App
    dir: "{{.APP_PROJECT_ROOT}}"
    cmds:
      - wails dev
      - rm -rf build/bin
    silent: true
    interactive: true

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
    silent: true

  build:
    desc: Build CLI and App for release
    cmds:
      - task: clean
      - mkdir -p {{.BUILD_DIR}}
      - echo "*" > {{.BUILD_DIR}}/.gitignore
      - cp -r .codefolio {{.BUILD_DIR}}/
      - cmd: cp .env {{.BUILD_DIR}}/
        if: test -f .env
      - task: build-app
      - task: build-cli
    silent: true

  build-cli:
    internal: true
    vars:
      EXT:
        sh: if [ "{{OS}}" = "windows" ]; then echo -n ".exe"; fi
    cmds:
      - go build -o {{.BUILD_DIR}}/codefolio{{.EXT}} {{.CLI_PROJECT_ROOT}}
    silent: true

  build-app:
    internal: true
    dir: "{{.APP_PROJECT_ROOT}}"
    cmds:
      - wails build > /dev/null
      - mv build/bin/* {{.BUILD_DIR}}/
      - rm -rf build/bin
    silent: true
