/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: D:\Workspace\local\codefolio\cpp\swig\yoga.swig */



#define SWIG_VERSION 0x040401
#define SWIGGO
#define SWIGMODULE yoga
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NOEXCEPT noexcept
#else
# define SWIG_NOEXCEPT throw()
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 *
 * Note that SWIG expects __cplusplus to be defined to the appropriate C++ standard.
 * MSVC users are urged to check and examine the /Zc:__cplusplus compiler option.
 * See https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef ptrdiff_t intgo;
typedef size_t uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include <yoga/Yoga.h>

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_yoga_95d702ff72525532(void *_swig_go_0) {
  void *arg1 = 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_yoga_95d702ff72525532(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


intgo _wrap_YGAlignAuto_yoga_95d702ff72525532() {
  enum YGAlign result;
  intgo _swig_go_result;
  
  
  result = YGAlignAuto;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGAlignFlexStart_yoga_95d702ff72525532() {
  enum YGAlign result;
  intgo _swig_go_result;
  
  
  result = YGAlignFlexStart;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGAlignCenter_yoga_95d702ff72525532() {
  enum YGAlign result;
  intgo _swig_go_result;
  
  
  result = YGAlignCenter;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGAlignFlexEnd_yoga_95d702ff72525532() {
  enum YGAlign result;
  intgo _swig_go_result;
  
  
  result = YGAlignFlexEnd;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGAlignStretch_yoga_95d702ff72525532() {
  enum YGAlign result;
  intgo _swig_go_result;
  
  
  result = YGAlignStretch;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGAlignBaseline_yoga_95d702ff72525532() {
  enum YGAlign result;
  intgo _swig_go_result;
  
  
  result = YGAlignBaseline;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGAlignSpaceBetween_yoga_95d702ff72525532() {
  enum YGAlign result;
  intgo _swig_go_result;
  
  
  result = YGAlignSpaceBetween;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGAlignSpaceAround_yoga_95d702ff72525532() {
  enum YGAlign result;
  intgo _swig_go_result;
  
  
  result = YGAlignSpaceAround;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGAlignSpaceEvenly_yoga_95d702ff72525532() {
  enum YGAlign result;
  intgo _swig_go_result;
  
  
  result = YGAlignSpaceEvenly;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGAlignStart_yoga_95d702ff72525532() {
  enum YGAlign result;
  intgo _swig_go_result;
  
  
  result = YGAlignStart;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGAlignEnd_yoga_95d702ff72525532() {
  enum YGAlign result;
  intgo _swig_go_result;
  
  
  result = YGAlignEnd;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGAlignToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGAlign arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGAlign)_swig_go_0; 
  
  result = (char *)YGAlignToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_YGBoxSizingBorderBox_yoga_95d702ff72525532() {
  enum YGBoxSizing result;
  intgo _swig_go_result;
  
  
  result = YGBoxSizingBorderBox;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGBoxSizingContentBox_yoga_95d702ff72525532() {
  enum YGBoxSizing result;
  intgo _swig_go_result;
  
  
  result = YGBoxSizingContentBox;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGBoxSizingToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGBoxSizing arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGBoxSizing)_swig_go_0; 
  
  result = (char *)YGBoxSizingToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_YGDimensionWidth_yoga_95d702ff72525532() {
  enum YGDimension result;
  intgo _swig_go_result;
  
  
  result = YGDimensionWidth;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGDimensionHeight_yoga_95d702ff72525532() {
  enum YGDimension result;
  intgo _swig_go_result;
  
  
  result = YGDimensionHeight;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGDimensionToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGDimension arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGDimension)_swig_go_0; 
  
  result = (char *)YGDimensionToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_YGDirectionInherit_yoga_95d702ff72525532() {
  enum YGDirection result;
  intgo _swig_go_result;
  
  
  result = YGDirectionInherit;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGDirectionLTR_yoga_95d702ff72525532() {
  enum YGDirection result;
  intgo _swig_go_result;
  
  
  result = YGDirectionLTR;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGDirectionRTL_yoga_95d702ff72525532() {
  enum YGDirection result;
  intgo _swig_go_result;
  
  
  result = YGDirectionRTL;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGDirectionToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGDirection arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGDirection)_swig_go_0; 
  
  result = (char *)YGDirectionToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_YGDisplayFlex_yoga_95d702ff72525532() {
  enum YGDisplay result;
  intgo _swig_go_result;
  
  
  result = YGDisplayFlex;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGDisplayNone_yoga_95d702ff72525532() {
  enum YGDisplay result;
  intgo _swig_go_result;
  
  
  result = YGDisplayNone;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGDisplayContents_yoga_95d702ff72525532() {
  enum YGDisplay result;
  intgo _swig_go_result;
  
  
  result = YGDisplayContents;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGDisplayGrid_yoga_95d702ff72525532() {
  enum YGDisplay result;
  intgo _swig_go_result;
  
  
  result = YGDisplayGrid;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGDisplayToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGDisplay arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGDisplay)_swig_go_0; 
  
  result = (char *)YGDisplayToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_YGEdgeLeft_yoga_95d702ff72525532() {
  enum YGEdge result;
  intgo _swig_go_result;
  
  
  result = YGEdgeLeft;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGEdgeTop_yoga_95d702ff72525532() {
  enum YGEdge result;
  intgo _swig_go_result;
  
  
  result = YGEdgeTop;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGEdgeRight_yoga_95d702ff72525532() {
  enum YGEdge result;
  intgo _swig_go_result;
  
  
  result = YGEdgeRight;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGEdgeBottom_yoga_95d702ff72525532() {
  enum YGEdge result;
  intgo _swig_go_result;
  
  
  result = YGEdgeBottom;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGEdgeStart_yoga_95d702ff72525532() {
  enum YGEdge result;
  intgo _swig_go_result;
  
  
  result = YGEdgeStart;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGEdgeEnd_yoga_95d702ff72525532() {
  enum YGEdge result;
  intgo _swig_go_result;
  
  
  result = YGEdgeEnd;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGEdgeHorizontal_yoga_95d702ff72525532() {
  enum YGEdge result;
  intgo _swig_go_result;
  
  
  result = YGEdgeHorizontal;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGEdgeVertical_yoga_95d702ff72525532() {
  enum YGEdge result;
  intgo _swig_go_result;
  
  
  result = YGEdgeVertical;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGEdgeAll_yoga_95d702ff72525532() {
  enum YGEdge result;
  intgo _swig_go_result;
  
  
  result = YGEdgeAll;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGEdgeToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGEdge arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGEdge)_swig_go_0; 
  
  result = (char *)YGEdgeToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_YGErrataNone_yoga_95d702ff72525532() {
  enum YGErrata result;
  intgo _swig_go_result;
  
  
  result = YGErrataNone;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGErrataStretchFlexBasis_yoga_95d702ff72525532() {
  enum YGErrata result;
  intgo _swig_go_result;
  
  
  result = YGErrataStretchFlexBasis;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGErrataAbsolutePositionWithoutInsetsExcludesPadding_yoga_95d702ff72525532() {
  enum YGErrata result;
  intgo _swig_go_result;
  
  
  result = YGErrataAbsolutePositionWithoutInsetsExcludesPadding;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGErrataAbsolutePercentAgainstInnerSize_yoga_95d702ff72525532() {
  enum YGErrata result;
  intgo _swig_go_result;
  
  
  result = YGErrataAbsolutePercentAgainstInnerSize;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGErrataMinSizeUndefinedInsteadOfAuto_yoga_95d702ff72525532() {
  enum YGErrata result;
  intgo _swig_go_result;
  
  
  result = YGErrataMinSizeUndefinedInsteadOfAuto;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGErrataAll_yoga_95d702ff72525532() {
  enum YGErrata result;
  intgo _swig_go_result;
  
  
  result = YGErrataAll;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGErrataClassic_yoga_95d702ff72525532() {
  enum YGErrata result;
  intgo _swig_go_result;
  
  
  result = YGErrataClassic;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGErrataToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGErrata arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGErrata)_swig_go_0; 
  
  result = (char *)YGErrataToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_YGExperimentalFeatureWebFlexBasis_yoga_95d702ff72525532() {
  enum YGExperimentalFeature result;
  intgo _swig_go_result;
  
  
  result = YGExperimentalFeatureWebFlexBasis;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGExperimentalFeatureFixFlexBasisFitContent_yoga_95d702ff72525532() {
  enum YGExperimentalFeature result;
  intgo _swig_go_result;
  
  
  result = YGExperimentalFeatureFixFlexBasisFitContent;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGExperimentalFeatureToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGExperimentalFeature arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGExperimentalFeature)_swig_go_0; 
  
  result = (char *)YGExperimentalFeatureToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_YGFlexDirectionColumn_yoga_95d702ff72525532() {
  enum YGFlexDirection result;
  intgo _swig_go_result;
  
  
  result = YGFlexDirectionColumn;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGFlexDirectionColumnReverse_yoga_95d702ff72525532() {
  enum YGFlexDirection result;
  intgo _swig_go_result;
  
  
  result = YGFlexDirectionColumnReverse;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGFlexDirectionRow_yoga_95d702ff72525532() {
  enum YGFlexDirection result;
  intgo _swig_go_result;
  
  
  result = YGFlexDirectionRow;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGFlexDirectionRowReverse_yoga_95d702ff72525532() {
  enum YGFlexDirection result;
  intgo _swig_go_result;
  
  
  result = YGFlexDirectionRowReverse;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGFlexDirectionToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGFlexDirection arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGFlexDirection)_swig_go_0; 
  
  result = (char *)YGFlexDirectionToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_YGGridTrackTypeAuto_yoga_95d702ff72525532() {
  enum YGGridTrackType result;
  intgo _swig_go_result;
  
  
  result = YGGridTrackTypeAuto;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGGridTrackTypePoints_yoga_95d702ff72525532() {
  enum YGGridTrackType result;
  intgo _swig_go_result;
  
  
  result = YGGridTrackTypePoints;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGGridTrackTypePercent_yoga_95d702ff72525532() {
  enum YGGridTrackType result;
  intgo _swig_go_result;
  
  
  result = YGGridTrackTypePercent;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGGridTrackTypeFr_yoga_95d702ff72525532() {
  enum YGGridTrackType result;
  intgo _swig_go_result;
  
  
  result = YGGridTrackTypeFr;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGGridTrackTypeMinmax_yoga_95d702ff72525532() {
  enum YGGridTrackType result;
  intgo _swig_go_result;
  
  
  result = YGGridTrackTypeMinmax;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGGridTrackTypeToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGGridTrackType arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGGridTrackType)_swig_go_0; 
  
  result = (char *)YGGridTrackTypeToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_YGGutterColumn_yoga_95d702ff72525532() {
  enum YGGutter result;
  intgo _swig_go_result;
  
  
  result = YGGutterColumn;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGGutterRow_yoga_95d702ff72525532() {
  enum YGGutter result;
  intgo _swig_go_result;
  
  
  result = YGGutterRow;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGGutterAll_yoga_95d702ff72525532() {
  enum YGGutter result;
  intgo _swig_go_result;
  
  
  result = YGGutterAll;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGGutterToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGGutter arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGGutter)_swig_go_0; 
  
  result = (char *)YGGutterToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_YGJustifyAuto_yoga_95d702ff72525532() {
  enum YGJustify result;
  intgo _swig_go_result;
  
  
  result = YGJustifyAuto;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGJustifyFlexStart_yoga_95d702ff72525532() {
  enum YGJustify result;
  intgo _swig_go_result;
  
  
  result = YGJustifyFlexStart;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGJustifyCenter_yoga_95d702ff72525532() {
  enum YGJustify result;
  intgo _swig_go_result;
  
  
  result = YGJustifyCenter;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGJustifyFlexEnd_yoga_95d702ff72525532() {
  enum YGJustify result;
  intgo _swig_go_result;
  
  
  result = YGJustifyFlexEnd;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGJustifySpaceBetween_yoga_95d702ff72525532() {
  enum YGJustify result;
  intgo _swig_go_result;
  
  
  result = YGJustifySpaceBetween;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGJustifySpaceAround_yoga_95d702ff72525532() {
  enum YGJustify result;
  intgo _swig_go_result;
  
  
  result = YGJustifySpaceAround;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGJustifySpaceEvenly_yoga_95d702ff72525532() {
  enum YGJustify result;
  intgo _swig_go_result;
  
  
  result = YGJustifySpaceEvenly;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGJustifyStretch_yoga_95d702ff72525532() {
  enum YGJustify result;
  intgo _swig_go_result;
  
  
  result = YGJustifyStretch;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGJustifyStart_yoga_95d702ff72525532() {
  enum YGJustify result;
  intgo _swig_go_result;
  
  
  result = YGJustifyStart;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGJustifyEnd_yoga_95d702ff72525532() {
  enum YGJustify result;
  intgo _swig_go_result;
  
  
  result = YGJustifyEnd;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGJustifyToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGJustify arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGJustify)_swig_go_0; 
  
  result = (char *)YGJustifyToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_YGLogLevelError_yoga_95d702ff72525532() {
  enum YGLogLevel result;
  intgo _swig_go_result;
  
  
  result = YGLogLevelError;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGLogLevelWarn_yoga_95d702ff72525532() {
  enum YGLogLevel result;
  intgo _swig_go_result;
  
  
  result = YGLogLevelWarn;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGLogLevelInfo_yoga_95d702ff72525532() {
  enum YGLogLevel result;
  intgo _swig_go_result;
  
  
  result = YGLogLevelInfo;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGLogLevelDebug_yoga_95d702ff72525532() {
  enum YGLogLevel result;
  intgo _swig_go_result;
  
  
  result = YGLogLevelDebug;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGLogLevelVerbose_yoga_95d702ff72525532() {
  enum YGLogLevel result;
  intgo _swig_go_result;
  
  
  result = YGLogLevelVerbose;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGLogLevelFatal_yoga_95d702ff72525532() {
  enum YGLogLevel result;
  intgo _swig_go_result;
  
  
  result = YGLogLevelFatal;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGLogLevelToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGLogLevel arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGLogLevel)_swig_go_0; 
  
  result = (char *)YGLogLevelToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_YGMeasureModeUndefined_yoga_95d702ff72525532() {
  enum YGMeasureMode result;
  intgo _swig_go_result;
  
  
  result = YGMeasureModeUndefined;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGMeasureModeExactly_yoga_95d702ff72525532() {
  enum YGMeasureMode result;
  intgo _swig_go_result;
  
  
  result = YGMeasureModeExactly;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGMeasureModeAtMost_yoga_95d702ff72525532() {
  enum YGMeasureMode result;
  intgo _swig_go_result;
  
  
  result = YGMeasureModeAtMost;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGMeasureModeToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGMeasureMode arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGMeasureMode)_swig_go_0; 
  
  result = (char *)YGMeasureModeToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_YGNodeTypeDefault_yoga_95d702ff72525532() {
  enum YGNodeType result;
  intgo _swig_go_result;
  
  
  result = YGNodeTypeDefault;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGNodeTypeText_yoga_95d702ff72525532() {
  enum YGNodeType result;
  intgo _swig_go_result;
  
  
  result = YGNodeTypeText;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGNodeTypeToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGNodeType arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGNodeType)_swig_go_0; 
  
  result = (char *)YGNodeTypeToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_YGOverflowVisible_yoga_95d702ff72525532() {
  enum YGOverflow result;
  intgo _swig_go_result;
  
  
  result = YGOverflowVisible;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGOverflowHidden_yoga_95d702ff72525532() {
  enum YGOverflow result;
  intgo _swig_go_result;
  
  
  result = YGOverflowHidden;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGOverflowScroll_yoga_95d702ff72525532() {
  enum YGOverflow result;
  intgo _swig_go_result;
  
  
  result = YGOverflowScroll;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGOverflowToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGOverflow arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGOverflow)_swig_go_0; 
  
  result = (char *)YGOverflowToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_YGPositionTypeStatic_yoga_95d702ff72525532() {
  enum YGPositionType result;
  intgo _swig_go_result;
  
  
  result = YGPositionTypeStatic;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGPositionTypeRelative_yoga_95d702ff72525532() {
  enum YGPositionType result;
  intgo _swig_go_result;
  
  
  result = YGPositionTypeRelative;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGPositionTypeAbsolute_yoga_95d702ff72525532() {
  enum YGPositionType result;
  intgo _swig_go_result;
  
  
  result = YGPositionTypeAbsolute;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGPositionTypeToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGPositionType arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGPositionType)_swig_go_0; 
  
  result = (char *)YGPositionTypeToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_YGUnitUndefined_yoga_95d702ff72525532() {
  enum YGUnit result;
  intgo _swig_go_result;
  
  
  result = YGUnitUndefined;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGUnitPoint_yoga_95d702ff72525532() {
  enum YGUnit result;
  intgo _swig_go_result;
  
  
  result = YGUnitPoint;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGUnitPercent_yoga_95d702ff72525532() {
  enum YGUnit result;
  intgo _swig_go_result;
  
  
  result = YGUnitPercent;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGUnitAuto_yoga_95d702ff72525532() {
  enum YGUnit result;
  intgo _swig_go_result;
  
  
  result = YGUnitAuto;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGUnitMaxContent_yoga_95d702ff72525532() {
  enum YGUnit result;
  intgo _swig_go_result;
  
  
  result = YGUnitMaxContent;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGUnitFitContent_yoga_95d702ff72525532() {
  enum YGUnit result;
  intgo _swig_go_result;
  
  
  result = YGUnitFitContent;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGUnitStretch_yoga_95d702ff72525532() {
  enum YGUnit result;
  intgo _swig_go_result;
  
  
  result = YGUnitStretch;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGUnitToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGUnit arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGUnit)_swig_go_0; 
  
  result = (char *)YGUnitToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_YGWrapNoWrap_yoga_95d702ff72525532() {
  enum YGWrap result;
  intgo _swig_go_result;
  
  
  result = YGWrapNoWrap;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGWrapWrap_yoga_95d702ff72525532() {
  enum YGWrap result;
  intgo _swig_go_result;
  
  
  result = YGWrapWrap;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_YGWrapWrapReverse_yoga_95d702ff72525532() {
  enum YGWrap result;
  intgo _swig_go_result;
  
  
  result = YGWrapWrapReverse;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


_gostring_ _wrap_YGWrapToString_yoga_95d702ff72525532(intgo _swig_go_0) {
  YGWrap arg1 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = (YGWrap)_swig_go_0; 
  
  result = (char *)YGWrapToString(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_YGValue_value_set_yoga_95d702ff72525532(struct YGValue *_swig_go_0, float _swig_go_1) {
  struct YGValue *arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(struct YGValue **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  if (arg1) (arg1)->value = arg2;
  
}


float _wrap_YGValue_value_get_yoga_95d702ff72525532(struct YGValue *_swig_go_0) {
  struct YGValue *arg1 = 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(struct YGValue **)&_swig_go_0; 
  
  result = (float) ((arg1)->value);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGValue_unit_set_yoga_95d702ff72525532(struct YGValue *_swig_go_0, intgo _swig_go_1) {
  struct YGValue *arg1 = 0 ;
  YGUnit arg2 ;
  
  arg1 = *(struct YGValue **)&_swig_go_0; 
  arg2 = (YGUnit)_swig_go_1; 
  
  if (arg1) (arg1)->unit = arg2;
  
}


intgo _wrap_YGValue_unit_get_yoga_95d702ff72525532(struct YGValue *_swig_go_0) {
  struct YGValue *arg1 = 0 ;
  YGUnit result;
  intgo _swig_go_result;
  
  arg1 = *(struct YGValue **)&_swig_go_0; 
  
  result = (YGUnit) ((arg1)->unit);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


struct YGValue *_wrap_new_YGValue_yoga_95d702ff72525532() {
  struct YGValue *result = 0 ;
  struct YGValue *_swig_go_result;
  
  
  result = (struct YGValue *)calloc(1, sizeof(struct YGValue));
  *(struct YGValue **)&_swig_go_result = (struct YGValue *)result; 
  return _swig_go_result;
}


void _wrap_delete_YGValue_yoga_95d702ff72525532(struct YGValue *_swig_go_0) {
  struct YGValue *arg1 = 0 ;
  
  arg1 = *(struct YGValue **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


struct YGValue *_wrap_YGValueAuto_get_yoga_95d702ff72525532() {
  YGValue *result = 0 ;
  struct YGValue *_swig_go_result;
  
  
  result = (YGValue *)&YGValueAuto;
  *(YGValue **)&_swig_go_result = (YGValue *)result; 
  return _swig_go_result;
}


struct YGValue *_wrap_YGValueUndefined_get_yoga_95d702ff72525532() {
  YGValue *result = 0 ;
  struct YGValue *_swig_go_result;
  
  
  result = (YGValue *)&YGValueUndefined;
  *(YGValue **)&_swig_go_result = (YGValue *)result; 
  return _swig_go_result;
}


struct YGValue *_wrap_YGValueZero_get_yoga_95d702ff72525532() {
  YGValue *result = 0 ;
  struct YGValue *_swig_go_result;
  
  
  result = (YGValue *)&YGValueZero;
  *(YGValue **)&_swig_go_result = (YGValue *)result; 
  return _swig_go_result;
}


bool _wrap_YGFloatIsUndefined_yoga_95d702ff72525532(float _swig_go_0) {
  float arg1 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = (float)_swig_go_0; 
  
  result = (bool)YGFloatIsUndefined(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct YGConfig *_wrap_YGConfigNew_yoga_95d702ff72525532() {
  YGConfigRef result;
  struct YGConfig *_swig_go_result;
  
  
  result = (YGConfigRef)YGConfigNew();
  *(YGConfigRef *)&_swig_go_result = (YGConfigRef)result; 
  return _swig_go_result;
}


void _wrap_YGConfigFree_yoga_95d702ff72525532(struct YGConfig *_swig_go_0) {
  YGConfigRef arg1 = 0 ;
  
  arg1 = *(YGConfigRef *)&_swig_go_0; 
  
  YGConfigFree(arg1);
  
}


struct YGConfig *_wrap_YGConfigGetDefault_yoga_95d702ff72525532() {
  YGConfigConstRef result;
  struct YGConfig *_swig_go_result;
  
  
  result = (YGConfigConstRef)YGConfigGetDefault();
  *(YGConfigConstRef *)&_swig_go_result = (YGConfigConstRef)result; 
  return _swig_go_result;
}


void _wrap_YGConfigSetUseWebDefaults_yoga_95d702ff72525532(struct YGConfig *_swig_go_0, bool _swig_go_1) {
  YGConfigRef arg1 = 0 ;
  bool arg2 ;
  
  arg1 = *(YGConfigRef *)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  YGConfigSetUseWebDefaults(arg1,arg2);
  
}


bool _wrap_YGConfigGetUseWebDefaults_yoga_95d702ff72525532(struct YGConfig *_swig_go_0) {
  YGConfigConstRef arg1 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(YGConfigConstRef *)&_swig_go_0; 
  
  result = (bool)YGConfigGetUseWebDefaults((struct YGConfig const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGConfigSetPointScaleFactor_yoga_95d702ff72525532(struct YGConfig *_swig_go_0, float _swig_go_1) {
  YGConfigRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGConfigRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGConfigSetPointScaleFactor(arg1,arg2);
  
}


float _wrap_YGConfigGetPointScaleFactor_yoga_95d702ff72525532(struct YGConfig *_swig_go_0) {
  YGConfigConstRef arg1 = 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGConfigConstRef *)&_swig_go_0; 
  
  result = (float)YGConfigGetPointScaleFactor((struct YGConfig const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGConfigSetErrata_yoga_95d702ff72525532(struct YGConfig *_swig_go_0, intgo _swig_go_1) {
  YGConfigRef arg1 = 0 ;
  YGErrata arg2 ;
  
  arg1 = *(YGConfigRef *)&_swig_go_0; 
  arg2 = (YGErrata)_swig_go_1; 
  
  YGConfigSetErrata(arg1,arg2);
  
}


intgo _wrap_YGConfigGetErrata_yoga_95d702ff72525532(struct YGConfig *_swig_go_0) {
  YGConfigConstRef arg1 = 0 ;
  YGErrata result;
  intgo _swig_go_result;
  
  arg1 = *(YGConfigConstRef *)&_swig_go_0; 
  
  result = (YGErrata)YGConfigGetErrata((struct YGConfig const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_YGConfigSetLogger_yoga_95d702ff72525532(struct YGConfig *_swig_go_0, void* _swig_go_1) {
  YGConfigRef arg1 = 0 ;
  YGLogger arg2 = 0 ;
  
  arg1 = *(YGConfigRef *)&_swig_go_0; 
  arg2 = *(YGLogger *)&_swig_go_1; 
  
  YGConfigSetLogger(arg1,arg2);
  
}


void _wrap_YGConfigSetContext_yoga_95d702ff72525532(struct YGConfig *_swig_go_0, void *_swig_go_1) {
  YGConfigRef arg1 = 0 ;
  void *arg2 = 0 ;
  
  arg1 = *(YGConfigRef *)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  
  YGConfigSetContext(arg1,arg2);
  
}


void *_wrap_YGConfigGetContext_yoga_95d702ff72525532(struct YGConfig *_swig_go_0) {
  YGConfigConstRef arg1 = 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(YGConfigConstRef *)&_swig_go_0; 
  
  result = (void *)YGConfigGetContext((struct YGConfig const *)arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_YGConfigSetExperimentalFeatureEnabled_yoga_95d702ff72525532(struct YGConfig *_swig_go_0, intgo _swig_go_1, bool _swig_go_2) {
  YGConfigRef arg1 = 0 ;
  YGExperimentalFeature arg2 ;
  bool arg3 ;
  
  arg1 = *(YGConfigRef *)&_swig_go_0; 
  arg2 = (YGExperimentalFeature)_swig_go_1; 
  arg3 = (bool)_swig_go_2; 
  
  YGConfigSetExperimentalFeatureEnabled(arg1,arg2,arg3);
  
}


bool _wrap_YGConfigIsExperimentalFeatureEnabled_yoga_95d702ff72525532(struct YGConfig *_swig_go_0, intgo _swig_go_1) {
  YGConfigConstRef arg1 = 0 ;
  YGExperimentalFeature arg2 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(YGConfigConstRef *)&_swig_go_0; 
  arg2 = (YGExperimentalFeature)_swig_go_1; 
  
  result = (bool)YGConfigIsExperimentalFeatureEnabled((struct YGConfig const *)arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGConfigSetCloneNodeFunc_yoga_95d702ff72525532(struct YGConfig *_swig_go_0, void* _swig_go_1) {
  YGConfigRef arg1 = 0 ;
  YGCloneNodeFunc arg2 = 0 ;
  
  arg1 = *(YGConfigRef *)&_swig_go_0; 
  arg2 = *(YGCloneNodeFunc *)&_swig_go_1; 
  
  YGConfigSetCloneNodeFunc(arg1,arg2);
  
}


struct YGNode *_wrap_YGNodeNew_yoga_95d702ff72525532() {
  YGNodeRef result;
  struct YGNode *_swig_go_result;
  
  
  result = (YGNodeRef)YGNodeNew();
  *(YGNodeRef *)&_swig_go_result = (YGNodeRef)result; 
  return _swig_go_result;
}


struct YGNode *_wrap_YGNodeNewWithConfig_yoga_95d702ff72525532(struct YGConfig *_swig_go_0) {
  YGConfigConstRef arg1 = 0 ;
  YGNodeRef result;
  struct YGNode *_swig_go_result;
  
  arg1 = *(YGConfigConstRef *)&_swig_go_0; 
  
  result = (YGNodeRef)YGNodeNewWithConfig((struct YGConfig const *)arg1);
  *(YGNodeRef *)&_swig_go_result = (YGNodeRef)result; 
  return _swig_go_result;
}


struct YGNode *_wrap_YGNodeClone_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGNodeRef result;
  struct YGNode *_swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (YGNodeRef)YGNodeClone((struct YGNode const *)arg1);
  *(YGNodeRef *)&_swig_go_result = (YGNodeRef)result; 
  return _swig_go_result;
}


void _wrap_YGNodeFree_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeFree(arg1);
  
}


void _wrap_YGNodeFreeRecursive_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeFreeRecursive(arg1);
  
}


void _wrap_YGNodeFinalize_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeFinalize(arg1);
  
}


void _wrap_YGNodeReset_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeReset(arg1);
  
}


void _wrap_YGNodeCalculateLayout_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1, float _swig_go_2, intgo _swig_go_3) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  float arg3 ;
  YGDirection arg4 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  arg3 = (float)_swig_go_2; 
  arg4 = (YGDirection)_swig_go_3; 
  
  YGNodeCalculateLayout(arg1,arg2,arg3,arg4);
  
}


bool _wrap_YGNodeGetHasNewLayout_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (bool)YGNodeGetHasNewLayout((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGNodeSetHasNewLayout_yoga_95d702ff72525532(struct YGNode *_swig_go_0, bool _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  bool arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  YGNodeSetHasNewLayout(arg1,arg2);
  
}


bool _wrap_YGNodeIsDirty_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (bool)YGNodeIsDirty((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGNodeMarkDirty_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeMarkDirty(arg1);
  
}


void _wrap_YGNodeSetDirtiedFunc_yoga_95d702ff72525532(struct YGNode *_swig_go_0, void* _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGDirtiedFunc arg2 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = *(YGDirtiedFunc *)&_swig_go_1; 
  
  YGNodeSetDirtiedFunc(arg1,arg2);
  
}


void* _wrap_YGNodeGetDirtiedFunc_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGDirtiedFunc result;
  void* _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (YGDirtiedFunc)YGNodeGetDirtiedFunc((struct YGNode const *)arg1);
  *(YGDirtiedFunc *)&_swig_go_result = (YGDirtiedFunc)result; 
  return _swig_go_result;
}


void _wrap_YGNodeInsertChild_yoga_95d702ff72525532(struct YGNode *_swig_go_0, struct YGNode *_swig_go_1, long long _swig_go_2) {
  YGNodeRef arg1 = 0 ;
  YGNodeRef arg2 = 0 ;
  size_t arg3 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = *(YGNodeRef *)&_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  
  YGNodeInsertChild(arg1,arg2,arg3);
  
}


void _wrap_YGNodeSwapChild_yoga_95d702ff72525532(struct YGNode *_swig_go_0, struct YGNode *_swig_go_1, long long _swig_go_2) {
  YGNodeRef arg1 = 0 ;
  YGNodeRef arg2 = 0 ;
  size_t arg3 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = *(YGNodeRef *)&_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  
  YGNodeSwapChild(arg1,arg2,arg3);
  
}


void _wrap_YGNodeRemoveChild_yoga_95d702ff72525532(struct YGNode *_swig_go_0, struct YGNode *_swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGNodeRef arg2 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = *(YGNodeRef *)&_swig_go_1; 
  
  YGNodeRemoveChild(arg1,arg2);
  
}


void _wrap_YGNodeRemoveAllChildren_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeRemoveAllChildren(arg1);
  
}


void _wrap_YGNodeSetChildren_yoga_95d702ff72525532(struct YGNode *_swig_go_0, YGNodeRef *_swig_go_1, long long _swig_go_2) {
  YGNodeRef arg1 = 0 ;
  YGNodeRef *arg2 = 0 ;
  size_t arg3 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = *(YGNodeRef **)&_swig_go_1; 
  arg3 = (size_t)_swig_go_2; 
  
  YGNodeSetChildren(arg1,(struct YGNode *const *)arg2,arg3);
  
}


struct YGNode *_wrap_YGNodeGetChild_yoga_95d702ff72525532(struct YGNode *_swig_go_0, long long _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  size_t arg2 ;
  YGNodeRef result;
  struct YGNode *_swig_go_result;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  result = (YGNodeRef)YGNodeGetChild(arg1,arg2);
  *(YGNodeRef *)&_swig_go_result = (YGNodeRef)result; 
  return _swig_go_result;
}


long long _wrap_YGNodeGetChildCount_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  size_t result;
  long long _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = YGNodeGetChildCount((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct YGNode *_wrap_YGNodeGetOwner_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  YGNodeRef result;
  struct YGNode *_swig_go_result;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  result = (YGNodeRef)YGNodeGetOwner(arg1);
  *(YGNodeRef *)&_swig_go_result = (YGNodeRef)result; 
  return _swig_go_result;
}


struct YGNode *_wrap_YGNodeGetParent_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  YGNodeRef result;
  struct YGNode *_swig_go_result;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  result = (YGNodeRef)YGNodeGetParent(arg1);
  *(YGNodeRef *)&_swig_go_result = (YGNodeRef)result; 
  return _swig_go_result;
}


void _wrap_YGNodeSetConfig_yoga_95d702ff72525532(struct YGNode *_swig_go_0, struct YGConfig *_swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGConfigRef arg2 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = *(YGConfigRef *)&_swig_go_1; 
  
  YGNodeSetConfig(arg1,arg2);
  
}


struct YGConfig *_wrap_YGNodeGetConfig_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  YGConfigConstRef result;
  struct YGConfig *_swig_go_result;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  result = (YGConfigConstRef)YGNodeGetConfig(arg1);
  *(YGConfigConstRef *)&_swig_go_result = (YGConfigConstRef)result; 
  return _swig_go_result;
}


void _wrap_YGNodeSetContext_yoga_95d702ff72525532(struct YGNode *_swig_go_0, void *_swig_go_1) {
  YGNodeRef arg1 = 0 ;
  void *arg2 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  
  YGNodeSetContext(arg1,arg2);
  
}


void *_wrap_YGNodeGetContext_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (void *)YGNodeGetContext((struct YGNode const *)arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_YGSize_width_set_yoga_95d702ff72525532(struct YGSize *_swig_go_0, float _swig_go_1) {
  struct YGSize *arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(struct YGSize **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  if (arg1) (arg1)->width = arg2;
  
}


float _wrap_YGSize_width_get_yoga_95d702ff72525532(struct YGSize *_swig_go_0) {
  struct YGSize *arg1 = 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(struct YGSize **)&_swig_go_0; 
  
  result = (float) ((arg1)->width);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGSize_height_set_yoga_95d702ff72525532(struct YGSize *_swig_go_0, float _swig_go_1) {
  struct YGSize *arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(struct YGSize **)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  if (arg1) (arg1)->height = arg2;
  
}


float _wrap_YGSize_height_get_yoga_95d702ff72525532(struct YGSize *_swig_go_0) {
  struct YGSize *arg1 = 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(struct YGSize **)&_swig_go_0; 
  
  result = (float) ((arg1)->height);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct YGSize *_wrap_new_YGSize_yoga_95d702ff72525532() {
  struct YGSize *result = 0 ;
  struct YGSize *_swig_go_result;
  
  
  result = (struct YGSize *)calloc(1, sizeof(struct YGSize));
  *(struct YGSize **)&_swig_go_result = (struct YGSize *)result; 
  return _swig_go_result;
}


void _wrap_delete_YGSize_yoga_95d702ff72525532(struct YGSize *_swig_go_0) {
  struct YGSize *arg1 = 0 ;
  
  arg1 = *(struct YGSize **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


void _wrap_YGNodeSetMeasureFunc_yoga_95d702ff72525532(struct YGNode *_swig_go_0, void* _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGMeasureFunc arg2 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = *(YGMeasureFunc *)&_swig_go_1; 
  
  YGNodeSetMeasureFunc(arg1,arg2);
  
}


bool _wrap_YGNodeHasMeasureFunc_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (bool)YGNodeHasMeasureFunc((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGNodeSetMinContentMeasureFunc_yoga_95d702ff72525532(struct YGNode *_swig_go_0, void* _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGMinContentMeasureFunc arg2 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = *(YGMinContentMeasureFunc *)&_swig_go_1; 
  
  YGNodeSetMinContentMeasureFunc(arg1,arg2);
  
}


bool _wrap_YGNodeHasMinContentMeasureFunc_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (bool)YGNodeHasMinContentMeasureFunc((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGNodeSetMinContentWidth_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeSetMinContentWidth(arg1,arg2);
  
}


void _wrap_YGNodeSetMinContentHeight_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeSetMinContentHeight(arg1,arg2);
  
}


float _wrap_YGNodeGetMinContentWidth_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (float)YGNodeGetMinContentWidth((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_YGNodeGetMinContentHeight_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (float)YGNodeGetMinContentHeight((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGNodeSetBaselineFunc_yoga_95d702ff72525532(struct YGNode *_swig_go_0, void* _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGBaselineFunc arg2 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = *(YGBaselineFunc *)&_swig_go_1; 
  
  YGNodeSetBaselineFunc(arg1,arg2);
  
}


bool _wrap_YGNodeHasBaselineFunc_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (bool)YGNodeHasBaselineFunc((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGNodeSetIsReferenceBaseline_yoga_95d702ff72525532(struct YGNode *_swig_go_0, bool _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  bool arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  YGNodeSetIsReferenceBaseline(arg1,arg2);
  
}


bool _wrap_YGNodeIsReferenceBaseline_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (bool)YGNodeIsReferenceBaseline((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGNodeSetNodeType_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGNodeType arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGNodeType)_swig_go_1; 
  
  YGNodeSetNodeType(arg1,arg2);
  
}


intgo _wrap_YGNodeGetNodeType_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGNodeType result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (YGNodeType)YGNodeGetNodeType((struct YGNode const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_YGNodeSetAlwaysFormsContainingBlock_yoga_95d702ff72525532(struct YGNode *_swig_go_0, bool _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  bool arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  YGNodeSetAlwaysFormsContainingBlock(arg1,arg2);
  
}


bool _wrap_YGNodeGetAlwaysFormsContainingBlock_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (bool)YGNodeGetAlwaysFormsContainingBlock((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


bool _wrap_YGNodeCanUseCachedMeasurement_yoga_95d702ff72525532(intgo _swig_go_0, float _swig_go_1, intgo _swig_go_2, float _swig_go_3, intgo _swig_go_4, float _swig_go_5, intgo _swig_go_6, float _swig_go_7, float _swig_go_8, float _swig_go_9, float _swig_go_10, float _swig_go_11, struct YGConfig *_swig_go_12) {
  YGMeasureMode arg1 ;
  float arg2 ;
  YGMeasureMode arg3 ;
  float arg4 ;
  YGMeasureMode arg5 ;
  float arg6 ;
  YGMeasureMode arg7 ;
  float arg8 ;
  float arg9 ;
  float arg10 ;
  float arg11 ;
  float arg12 ;
  YGConfigRef arg13 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = (YGMeasureMode)_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  arg3 = (YGMeasureMode)_swig_go_2; 
  arg4 = (float)_swig_go_3; 
  arg5 = (YGMeasureMode)_swig_go_4; 
  arg6 = (float)_swig_go_5; 
  arg7 = (YGMeasureMode)_swig_go_6; 
  arg8 = (float)_swig_go_7; 
  arg9 = (float)_swig_go_8; 
  arg10 = (float)_swig_go_9; 
  arg11 = (float)_swig_go_10; 
  arg12 = (float)_swig_go_11; 
  arg13 = *(YGConfigRef *)&_swig_go_12; 
  
  result = (bool)YGNodeCanUseCachedMeasurement(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGNodeCopyStyle_yoga_95d702ff72525532(struct YGNode *_swig_go_0, struct YGNode *_swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGNodeConstRef arg2 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = *(YGNodeConstRef *)&_swig_go_1; 
  
  YGNodeCopyStyle(arg1,(struct YGNode const *)arg2);
  
}


void _wrap_YGNodeStyleSetDirection_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGDirection arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGDirection)_swig_go_1; 
  
  YGNodeStyleSetDirection(arg1,arg2);
  
}


intgo _wrap_YGNodeStyleGetDirection_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGDirection result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (YGDirection)YGNodeStyleGetDirection((struct YGNode const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetFlexDirection_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGFlexDirection arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGFlexDirection)_swig_go_1; 
  
  YGNodeStyleSetFlexDirection(arg1,arg2);
  
}


intgo _wrap_YGNodeStyleGetFlexDirection_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGFlexDirection result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (YGFlexDirection)YGNodeStyleGetFlexDirection((struct YGNode const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetJustifyContent_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGJustify arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGJustify)_swig_go_1; 
  
  YGNodeStyleSetJustifyContent(arg1,arg2);
  
}


intgo _wrap_YGNodeStyleGetJustifyContent_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGJustify result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (YGJustify)YGNodeStyleGetJustifyContent((struct YGNode const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetJustifyItems_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGJustify arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGJustify)_swig_go_1; 
  
  YGNodeStyleSetJustifyItems(arg1,arg2);
  
}


intgo _wrap_YGNodeStyleGetJustifyItems_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGJustify result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (YGJustify)YGNodeStyleGetJustifyItems((struct YGNode const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetJustifySelf_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGJustify arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGJustify)_swig_go_1; 
  
  YGNodeStyleSetJustifySelf(arg1,arg2);
  
}


intgo _wrap_YGNodeStyleGetJustifySelf_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGJustify result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (YGJustify)YGNodeStyleGetJustifySelf((struct YGNode const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetAlignContent_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGAlign arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGAlign)_swig_go_1; 
  
  YGNodeStyleSetAlignContent(arg1,arg2);
  
}


intgo _wrap_YGNodeStyleGetAlignContent_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGAlign result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (YGAlign)YGNodeStyleGetAlignContent((struct YGNode const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetAlignItems_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGAlign arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGAlign)_swig_go_1; 
  
  YGNodeStyleSetAlignItems(arg1,arg2);
  
}


intgo _wrap_YGNodeStyleGetAlignItems_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGAlign result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (YGAlign)YGNodeStyleGetAlignItems((struct YGNode const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetAlignSelf_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGAlign arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGAlign)_swig_go_1; 
  
  YGNodeStyleSetAlignSelf(arg1,arg2);
  
}


intgo _wrap_YGNodeStyleGetAlignSelf_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGAlign result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (YGAlign)YGNodeStyleGetAlignSelf((struct YGNode const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetPositionType_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGPositionType arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGPositionType)_swig_go_1; 
  
  YGNodeStyleSetPositionType(arg1,arg2);
  
}


intgo _wrap_YGNodeStyleGetPositionType_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGPositionType result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (YGPositionType)YGNodeStyleGetPositionType((struct YGNode const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetFlexWrap_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGWrap arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGWrap)_swig_go_1; 
  
  YGNodeStyleSetFlexWrap(arg1,arg2);
  
}


intgo _wrap_YGNodeStyleGetFlexWrap_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGWrap result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (YGWrap)YGNodeStyleGetFlexWrap((struct YGNode const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetOverflow_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGOverflow arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGOverflow)_swig_go_1; 
  
  YGNodeStyleSetOverflow(arg1,arg2);
  
}


intgo _wrap_YGNodeStyleGetOverflow_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGOverflow result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (YGOverflow)YGNodeStyleGetOverflow((struct YGNode const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetDisplay_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGDisplay arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGDisplay)_swig_go_1; 
  
  YGNodeStyleSetDisplay(arg1,arg2);
  
}


intgo _wrap_YGNodeStyleGetDisplay_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGDisplay result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (YGDisplay)YGNodeStyleGetDisplay((struct YGNode const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetFlex_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeStyleSetFlex(arg1,arg2);
  
}


float _wrap_YGNodeStyleGetFlex_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (float)YGNodeStyleGetFlex((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetFlexGrow_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeStyleSetFlexGrow(arg1,arg2);
  
}


float _wrap_YGNodeStyleGetFlexGrow_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (float)YGNodeStyleGetFlexGrow((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetFlexShrink_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeStyleSetFlexShrink(arg1,arg2);
  
}


float _wrap_YGNodeStyleGetFlexShrink_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (float)YGNodeStyleGetFlexShrink((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetFlexBasis_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeStyleSetFlexBasis(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetFlexBasisPercent_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeStyleSetFlexBasisPercent(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetFlexBasisAuto_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetFlexBasisAuto(arg1);
  
}


void _wrap_YGNodeStyleSetFlexBasisMaxContent_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetFlexBasisMaxContent(arg1);
  
}


void _wrap_YGNodeStyleSetFlexBasisFitContent_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetFlexBasisFitContent(arg1);
  
}


void _wrap_YGNodeStyleSetFlexBasisStretch_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetFlexBasisStretch(arg1);
  
}


struct YGValue *_wrap_YGNodeStyleGetFlexBasis_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGValue result;
  struct YGValue *_swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = YGNodeStyleGetFlexBasis((struct YGNode const *)arg1);
  {
    YGValue * resultptr = (YGValue *)malloc(sizeof(YGValue));
    memmove(resultptr, &result, sizeof(YGValue));
    *(YGValue **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetPosition_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1, float _swig_go_2) {
  YGNodeRef arg1 = 0 ;
  YGEdge arg2 ;
  float arg3 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGEdge)_swig_go_1; 
  arg3 = (float)_swig_go_2; 
  
  YGNodeStyleSetPosition(arg1,arg2,arg3);
  
}


void _wrap_YGNodeStyleSetPositionPercent_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1, float _swig_go_2) {
  YGNodeRef arg1 = 0 ;
  YGEdge arg2 ;
  float arg3 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGEdge)_swig_go_1; 
  arg3 = (float)_swig_go_2; 
  
  YGNodeStyleSetPositionPercent(arg1,arg2,arg3);
  
}


struct YGValue *_wrap_YGNodeStyleGetPosition_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeConstRef arg1 = 0 ;
  YGEdge arg2 ;
  YGValue result;
  struct YGValue *_swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  arg2 = (YGEdge)_swig_go_1; 
  
  result = YGNodeStyleGetPosition((struct YGNode const *)arg1,arg2);
  {
    YGValue * resultptr = (YGValue *)malloc(sizeof(YGValue));
    memmove(resultptr, &result, sizeof(YGValue));
    *(YGValue **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetPositionAuto_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGEdge arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGEdge)_swig_go_1; 
  
  YGNodeStyleSetPositionAuto(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetMargin_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1, float _swig_go_2) {
  YGNodeRef arg1 = 0 ;
  YGEdge arg2 ;
  float arg3 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGEdge)_swig_go_1; 
  arg3 = (float)_swig_go_2; 
  
  YGNodeStyleSetMargin(arg1,arg2,arg3);
  
}


void _wrap_YGNodeStyleSetMarginPercent_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1, float _swig_go_2) {
  YGNodeRef arg1 = 0 ;
  YGEdge arg2 ;
  float arg3 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGEdge)_swig_go_1; 
  arg3 = (float)_swig_go_2; 
  
  YGNodeStyleSetMarginPercent(arg1,arg2,arg3);
  
}


void _wrap_YGNodeStyleSetMarginAuto_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGEdge arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGEdge)_swig_go_1; 
  
  YGNodeStyleSetMarginAuto(arg1,arg2);
  
}


struct YGValue *_wrap_YGNodeStyleGetMargin_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeConstRef arg1 = 0 ;
  YGEdge arg2 ;
  YGValue result;
  struct YGValue *_swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  arg2 = (YGEdge)_swig_go_1; 
  
  result = YGNodeStyleGetMargin((struct YGNode const *)arg1,arg2);
  {
    YGValue * resultptr = (YGValue *)malloc(sizeof(YGValue));
    memmove(resultptr, &result, sizeof(YGValue));
    *(YGValue **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetPadding_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1, float _swig_go_2) {
  YGNodeRef arg1 = 0 ;
  YGEdge arg2 ;
  float arg3 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGEdge)_swig_go_1; 
  arg3 = (float)_swig_go_2; 
  
  YGNodeStyleSetPadding(arg1,arg2,arg3);
  
}


void _wrap_YGNodeStyleSetPaddingPercent_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1, float _swig_go_2) {
  YGNodeRef arg1 = 0 ;
  YGEdge arg2 ;
  float arg3 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGEdge)_swig_go_1; 
  arg3 = (float)_swig_go_2; 
  
  YGNodeStyleSetPaddingPercent(arg1,arg2,arg3);
  
}


struct YGValue *_wrap_YGNodeStyleGetPadding_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeConstRef arg1 = 0 ;
  YGEdge arg2 ;
  YGValue result;
  struct YGValue *_swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  arg2 = (YGEdge)_swig_go_1; 
  
  result = YGNodeStyleGetPadding((struct YGNode const *)arg1,arg2);
  {
    YGValue * resultptr = (YGValue *)malloc(sizeof(YGValue));
    memmove(resultptr, &result, sizeof(YGValue));
    *(YGValue **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetBorder_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1, float _swig_go_2) {
  YGNodeRef arg1 = 0 ;
  YGEdge arg2 ;
  float arg3 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGEdge)_swig_go_1; 
  arg3 = (float)_swig_go_2; 
  
  YGNodeStyleSetBorder(arg1,arg2,arg3);
  
}


float _wrap_YGNodeStyleGetBorder_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeConstRef arg1 = 0 ;
  YGEdge arg2 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  arg2 = (YGEdge)_swig_go_1; 
  
  result = (float)YGNodeStyleGetBorder((struct YGNode const *)arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetGap_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1, float _swig_go_2) {
  YGNodeRef arg1 = 0 ;
  YGGutter arg2 ;
  float arg3 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGGutter)_swig_go_1; 
  arg3 = (float)_swig_go_2; 
  
  YGNodeStyleSetGap(arg1,arg2,arg3);
  
}


void _wrap_YGNodeStyleSetGapPercent_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1, float _swig_go_2) {
  YGNodeRef arg1 = 0 ;
  YGGutter arg2 ;
  float arg3 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGGutter)_swig_go_1; 
  arg3 = (float)_swig_go_2; 
  
  YGNodeStyleSetGapPercent(arg1,arg2,arg3);
  
}


struct YGValue *_wrap_YGNodeStyleGetGap_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeConstRef arg1 = 0 ;
  YGGutter arg2 ;
  YGValue result;
  struct YGValue *_swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  arg2 = (YGGutter)_swig_go_1; 
  
  result = YGNodeStyleGetGap((struct YGNode const *)arg1,arg2);
  {
    YGValue * resultptr = (YGValue *)malloc(sizeof(YGValue));
    memmove(resultptr, &result, sizeof(YGValue));
    *(YGValue **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetBoxSizing_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  YGBoxSizing arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (YGBoxSizing)_swig_go_1; 
  
  YGNodeStyleSetBoxSizing(arg1,arg2);
  
}


intgo _wrap_YGNodeStyleGetBoxSizing_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGBoxSizing result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (YGBoxSizing)YGNodeStyleGetBoxSizing((struct YGNode const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetWidth_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeStyleSetWidth(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetWidthPercent_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeStyleSetWidthPercent(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetWidthAuto_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetWidthAuto(arg1);
  
}


void _wrap_YGNodeStyleSetWidthMaxContent_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetWidthMaxContent(arg1);
  
}


void _wrap_YGNodeStyleSetWidthFitContent_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetWidthFitContent(arg1);
  
}


void _wrap_YGNodeStyleSetWidthStretch_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetWidthStretch(arg1);
  
}


struct YGValue *_wrap_YGNodeStyleGetWidth_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGValue result;
  struct YGValue *_swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = YGNodeStyleGetWidth((struct YGNode const *)arg1);
  {
    YGValue * resultptr = (YGValue *)malloc(sizeof(YGValue));
    memmove(resultptr, &result, sizeof(YGValue));
    *(YGValue **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetHeight_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeStyleSetHeight(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetHeightPercent_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeStyleSetHeightPercent(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetHeightAuto_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetHeightAuto(arg1);
  
}


void _wrap_YGNodeStyleSetHeightMaxContent_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetHeightMaxContent(arg1);
  
}


void _wrap_YGNodeStyleSetHeightFitContent_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetHeightFitContent(arg1);
  
}


void _wrap_YGNodeStyleSetHeightStretch_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetHeightStretch(arg1);
  
}


struct YGValue *_wrap_YGNodeStyleGetHeight_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGValue result;
  struct YGValue *_swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = YGNodeStyleGetHeight((struct YGNode const *)arg1);
  {
    YGValue * resultptr = (YGValue *)malloc(sizeof(YGValue));
    memmove(resultptr, &result, sizeof(YGValue));
    *(YGValue **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetMinWidth_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeStyleSetMinWidth(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetMinWidthPercent_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeStyleSetMinWidthPercent(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetMinWidthMaxContent_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetMinWidthMaxContent(arg1);
  
}


void _wrap_YGNodeStyleSetMinWidthFitContent_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetMinWidthFitContent(arg1);
  
}


void _wrap_YGNodeStyleSetMinWidthStretch_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetMinWidthStretch(arg1);
  
}


struct YGValue *_wrap_YGNodeStyleGetMinWidth_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGValue result;
  struct YGValue *_swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = YGNodeStyleGetMinWidth((struct YGNode const *)arg1);
  {
    YGValue * resultptr = (YGValue *)malloc(sizeof(YGValue));
    memmove(resultptr, &result, sizeof(YGValue));
    *(YGValue **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetMinHeight_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeStyleSetMinHeight(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetMinHeightPercent_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeStyleSetMinHeightPercent(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetMinHeightMaxContent_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetMinHeightMaxContent(arg1);
  
}


void _wrap_YGNodeStyleSetMinHeightFitContent_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetMinHeightFitContent(arg1);
  
}


void _wrap_YGNodeStyleSetMinHeightStretch_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetMinHeightStretch(arg1);
  
}


struct YGValue *_wrap_YGNodeStyleGetMinHeight_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGValue result;
  struct YGValue *_swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = YGNodeStyleGetMinHeight((struct YGNode const *)arg1);
  {
    YGValue * resultptr = (YGValue *)malloc(sizeof(YGValue));
    memmove(resultptr, &result, sizeof(YGValue));
    *(YGValue **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetMaxWidth_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeStyleSetMaxWidth(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetMaxWidthPercent_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeStyleSetMaxWidthPercent(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetMaxWidthMaxContent_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetMaxWidthMaxContent(arg1);
  
}


void _wrap_YGNodeStyleSetMaxWidthFitContent_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetMaxWidthFitContent(arg1);
  
}


void _wrap_YGNodeStyleSetMaxWidthStretch_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetMaxWidthStretch(arg1);
  
}


struct YGValue *_wrap_YGNodeStyleGetMaxWidth_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGValue result;
  struct YGValue *_swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = YGNodeStyleGetMaxWidth((struct YGNode const *)arg1);
  {
    YGValue * resultptr = (YGValue *)malloc(sizeof(YGValue));
    memmove(resultptr, &result, sizeof(YGValue));
    *(YGValue **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetMaxHeight_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeStyleSetMaxHeight(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetMaxHeightPercent_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeStyleSetMaxHeightPercent(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetMaxHeightMaxContent_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetMaxHeightMaxContent(arg1);
  
}


void _wrap_YGNodeStyleSetMaxHeightFitContent_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetMaxHeightFitContent(arg1);
  
}


void _wrap_YGNodeStyleSetMaxHeightStretch_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetMaxHeightStretch(arg1);
  
}


struct YGValue *_wrap_YGNodeStyleGetMaxHeight_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGValue result;
  struct YGValue *_swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = YGNodeStyleGetMaxHeight((struct YGNode const *)arg1);
  {
    YGValue * resultptr = (YGValue *)malloc(sizeof(YGValue));
    memmove(resultptr, &result, sizeof(YGValue));
    *(YGValue **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetAspectRatio_yoga_95d702ff72525532(struct YGNode *_swig_go_0, float _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  float arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (float)_swig_go_1; 
  
  YGNodeStyleSetAspectRatio(arg1,arg2);
  
}


float _wrap_YGNodeStyleGetAspectRatio_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (float)YGNodeStyleGetAspectRatio((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetGridColumnStart_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  int arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  YGNodeStyleSetGridColumnStart(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetGridColumnStartAuto_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetGridColumnStartAuto(arg1);
  
}


void _wrap_YGNodeStyleSetGridColumnStartSpan_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  int arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  YGNodeStyleSetGridColumnStartSpan(arg1,arg2);
  
}


intgo _wrap_YGNodeStyleGetGridColumnStart_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (int)YGNodeStyleGetGridColumnStart((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetGridColumnEnd_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  int arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  YGNodeStyleSetGridColumnEnd(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetGridColumnEndAuto_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetGridColumnEndAuto(arg1);
  
}


void _wrap_YGNodeStyleSetGridColumnEndSpan_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  int arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  YGNodeStyleSetGridColumnEndSpan(arg1,arg2);
  
}


intgo _wrap_YGNodeStyleGetGridColumnEnd_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (int)YGNodeStyleGetGridColumnEnd((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetGridRowStart_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  int arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  YGNodeStyleSetGridRowStart(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetGridRowStartAuto_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetGridRowStartAuto(arg1);
  
}


void _wrap_YGNodeStyleSetGridRowStartSpan_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  int arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  YGNodeStyleSetGridRowStartSpan(arg1,arg2);
  
}


intgo _wrap_YGNodeStyleGetGridRowStart_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (int)YGNodeStyleGetGridRowStart((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetGridRowEnd_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  int arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  YGNodeStyleSetGridRowEnd(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetGridRowEndAuto_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeRef arg1 = 0 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  
  YGNodeStyleSetGridRowEndAuto(arg1);
  
}


void _wrap_YGNodeStyleSetGridRowEndSpan_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  int arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  YGNodeStyleSetGridRowEndSpan(arg1,arg2);
  
}


intgo _wrap_YGNodeStyleGetGridRowEnd_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (int)YGNodeStyleGetGridRowEnd((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_YGNodeStyleSetGridTemplateColumnsCount_yoga_95d702ff72525532(struct YGNode *_swig_go_0, long long _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  size_t arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  YGNodeStyleSetGridTemplateColumnsCount(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetGridTemplateColumn_yoga_95d702ff72525532(struct YGNode *_swig_go_0, long long _swig_go_1, intgo _swig_go_2, float _swig_go_3) {
  YGNodeRef arg1 = 0 ;
  size_t arg2 ;
  YGGridTrackType arg3 ;
  float arg4 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  arg3 = (YGGridTrackType)_swig_go_2; 
  arg4 = (float)_swig_go_3; 
  
  YGNodeStyleSetGridTemplateColumn(arg1,arg2,arg3,arg4);
  
}


void _wrap_YGNodeStyleSetGridTemplateColumnMinMax_yoga_95d702ff72525532(struct YGNode *_swig_go_0, long long _swig_go_1, intgo _swig_go_2, float _swig_go_3, intgo _swig_go_4, float _swig_go_5) {
  YGNodeRef arg1 = 0 ;
  size_t arg2 ;
  YGGridTrackType arg3 ;
  float arg4 ;
  YGGridTrackType arg5 ;
  float arg6 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  arg3 = (YGGridTrackType)_swig_go_2; 
  arg4 = (float)_swig_go_3; 
  arg5 = (YGGridTrackType)_swig_go_4; 
  arg6 = (float)_swig_go_5; 
  
  YGNodeStyleSetGridTemplateColumnMinMax(arg1,arg2,arg3,arg4,arg5,arg6);
  
}


void _wrap_YGNodeStyleSetGridTemplateRowsCount_yoga_95d702ff72525532(struct YGNode *_swig_go_0, long long _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  size_t arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  YGNodeStyleSetGridTemplateRowsCount(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetGridTemplateRow_yoga_95d702ff72525532(struct YGNode *_swig_go_0, long long _swig_go_1, intgo _swig_go_2, float _swig_go_3) {
  YGNodeRef arg1 = 0 ;
  size_t arg2 ;
  YGGridTrackType arg3 ;
  float arg4 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  arg3 = (YGGridTrackType)_swig_go_2; 
  arg4 = (float)_swig_go_3; 
  
  YGNodeStyleSetGridTemplateRow(arg1,arg2,arg3,arg4);
  
}


void _wrap_YGNodeStyleSetGridTemplateRowMinMax_yoga_95d702ff72525532(struct YGNode *_swig_go_0, long long _swig_go_1, intgo _swig_go_2, float _swig_go_3, intgo _swig_go_4, float _swig_go_5) {
  YGNodeRef arg1 = 0 ;
  size_t arg2 ;
  YGGridTrackType arg3 ;
  float arg4 ;
  YGGridTrackType arg5 ;
  float arg6 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  arg3 = (YGGridTrackType)_swig_go_2; 
  arg4 = (float)_swig_go_3; 
  arg5 = (YGGridTrackType)_swig_go_4; 
  arg6 = (float)_swig_go_5; 
  
  YGNodeStyleSetGridTemplateRowMinMax(arg1,arg2,arg3,arg4,arg5,arg6);
  
}


void _wrap_YGNodeStyleSetGridAutoColumnsCount_yoga_95d702ff72525532(struct YGNode *_swig_go_0, long long _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  size_t arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  YGNodeStyleSetGridAutoColumnsCount(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetGridAutoColumn_yoga_95d702ff72525532(struct YGNode *_swig_go_0, long long _swig_go_1, intgo _swig_go_2, float _swig_go_3) {
  YGNodeRef arg1 = 0 ;
  size_t arg2 ;
  YGGridTrackType arg3 ;
  float arg4 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  arg3 = (YGGridTrackType)_swig_go_2; 
  arg4 = (float)_swig_go_3; 
  
  YGNodeStyleSetGridAutoColumn(arg1,arg2,arg3,arg4);
  
}


void _wrap_YGNodeStyleSetGridAutoColumnMinMax_yoga_95d702ff72525532(struct YGNode *_swig_go_0, long long _swig_go_1, intgo _swig_go_2, float _swig_go_3, intgo _swig_go_4, float _swig_go_5) {
  YGNodeRef arg1 = 0 ;
  size_t arg2 ;
  YGGridTrackType arg3 ;
  float arg4 ;
  YGGridTrackType arg5 ;
  float arg6 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  arg3 = (YGGridTrackType)_swig_go_2; 
  arg4 = (float)_swig_go_3; 
  arg5 = (YGGridTrackType)_swig_go_4; 
  arg6 = (float)_swig_go_5; 
  
  YGNodeStyleSetGridAutoColumnMinMax(arg1,arg2,arg3,arg4,arg5,arg6);
  
}


void _wrap_YGNodeStyleSetGridAutoRowsCount_yoga_95d702ff72525532(struct YGNode *_swig_go_0, long long _swig_go_1) {
  YGNodeRef arg1 = 0 ;
  size_t arg2 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  YGNodeStyleSetGridAutoRowsCount(arg1,arg2);
  
}


void _wrap_YGNodeStyleSetGridAutoRow_yoga_95d702ff72525532(struct YGNode *_swig_go_0, long long _swig_go_1, intgo _swig_go_2, float _swig_go_3) {
  YGNodeRef arg1 = 0 ;
  size_t arg2 ;
  YGGridTrackType arg3 ;
  float arg4 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  arg3 = (YGGridTrackType)_swig_go_2; 
  arg4 = (float)_swig_go_3; 
  
  YGNodeStyleSetGridAutoRow(arg1,arg2,arg3,arg4);
  
}


void _wrap_YGNodeStyleSetGridAutoRowMinMax_yoga_95d702ff72525532(struct YGNode *_swig_go_0, long long _swig_go_1, intgo _swig_go_2, float _swig_go_3, intgo _swig_go_4, float _swig_go_5) {
  YGNodeRef arg1 = 0 ;
  size_t arg2 ;
  YGGridTrackType arg3 ;
  float arg4 ;
  YGGridTrackType arg5 ;
  float arg6 ;
  
  arg1 = *(YGNodeRef *)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  arg3 = (YGGridTrackType)_swig_go_2; 
  arg4 = (float)_swig_go_3; 
  arg5 = (YGGridTrackType)_swig_go_4; 
  arg6 = (float)_swig_go_5; 
  
  YGNodeStyleSetGridAutoRowMinMax(arg1,arg2,arg3,arg4,arg5,arg6);
  
}


float _wrap_YGNodeLayoutGetLeft_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (float)YGNodeLayoutGetLeft((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_YGNodeLayoutGetTop_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (float)YGNodeLayoutGetTop((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_YGNodeLayoutGetRight_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (float)YGNodeLayoutGetRight((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_YGNodeLayoutGetBottom_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (float)YGNodeLayoutGetBottom((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_YGNodeLayoutGetWidth_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (float)YGNodeLayoutGetWidth((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_YGNodeLayoutGetHeight_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (float)YGNodeLayoutGetHeight((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_YGNodeLayoutGetDirection_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  YGDirection result;
  intgo _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (YGDirection)YGNodeLayoutGetDirection((struct YGNode const *)arg1);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


bool _wrap_YGNodeLayoutGetHadOverflow_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (bool)YGNodeLayoutGetHadOverflow((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_YGNodeLayoutGetMargin_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeConstRef arg1 = 0 ;
  YGEdge arg2 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  arg2 = (YGEdge)_swig_go_1; 
  
  result = (float)YGNodeLayoutGetMargin((struct YGNode const *)arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_YGNodeLayoutGetBorder_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeConstRef arg1 = 0 ;
  YGEdge arg2 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  arg2 = (YGEdge)_swig_go_1; 
  
  result = (float)YGNodeLayoutGetBorder((struct YGNode const *)arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_YGNodeLayoutGetPadding_yoga_95d702ff72525532(struct YGNode *_swig_go_0, intgo _swig_go_1) {
  YGNodeConstRef arg1 = 0 ;
  YGEdge arg2 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  arg2 = (YGEdge)_swig_go_1; 
  
  result = (float)YGNodeLayoutGetPadding((struct YGNode const *)arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_YGNodeLayoutGetRawHeight_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (float)YGNodeLayoutGetRawHeight((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_YGNodeLayoutGetRawWidth_yoga_95d702ff72525532(struct YGNode *_swig_go_0) {
  YGNodeConstRef arg1 = 0 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(YGNodeConstRef *)&_swig_go_0; 
  
  result = (float)YGNodeLayoutGetRawWidth((struct YGNode const *)arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_YGRoundValueToPixelGrid_yoga_95d702ff72525532(double _swig_go_0, double _swig_go_1, bool _swig_go_2, bool _swig_go_3) {
  double arg1 ;
  double arg2 ;
  bool arg3 ;
  bool arg4 ;
  float result;
  float _swig_go_result;
  
  arg1 = (double)_swig_go_0; 
  arg2 = (double)_swig_go_1; 
  arg3 = (bool)_swig_go_2; 
  arg4 = (bool)_swig_go_3; 
  
  result = (float)YGRoundValueToPixelGrid(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

