// Code generated by tui generate. DO NOT EDIT.
// Source: app.gsx

package components

import (
	tui "github.com/grindlemire/go-tui"
)

type app struct{}

func App() *app { return new(app) }

func (a *app) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.On(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
	}
}

func (a *app) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithWidthPercent(100.00),
		tui.WithHeightPercent(100.00),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithAlign(tui.AlignCenter),
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithGap(1),
	)
	__tui_1 := tui.New(
		tui.WithText("Hello, TUI!"),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText("Press Esc to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_2)

	return __tui_0
}

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*app)(nil)
)
