// Code generated by tui generate. DO NOT EDIT.
// Source: composer.gsx

package components

import (
	tui "github.com/grindlemire/go-tui"
)

type ComposerView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
	R         *tui.Element
}

func (v *ComposerView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ComposerView) GetRoot() *tui.Element { return v.Root }

func (v *ComposerView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ComposerView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ComposerView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ComposerView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ComposerView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
	v.R = f.R
}

var _ tui.AppBinder = (*ComposerView)(nil)

var _ tui.AppUnbinder = (*ComposerView)(nil)

var _ tui.PropsUpdater = (*ComposerView)(nil)

func Composer(r *tui.Ref, children []*tui.Element) *ComposerView {
	var view ComposerView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithPadding(1),
		tui.WithBackground(tui.NewStyle().Background(tui.RGBColor(33, 33, 33))),
	)
	r.Set(__tui_0)
	for _, __child := range children {
		__tui_0.AddChild(__child)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = ComposerView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
		R:         r.El(),
	}
	return &view
}
