// Code generated by tux compile. DO NOT EDIT.

package components

import (
	"github.com/cylixlee/tux/builtin"
	"github.com/cylixlee/tux/renderer"
	"github.com/cylixlee/tux/style"
)

func (self *Header) Render(ctx renderer.Context) *renderer.Element {
	return builtin.CreateRow(ctx, builtin.RowProps{
		Key: "header",
		Gap: 2,
	},
		builtin.CreateText(ctx, builtin.TextProps{
			Text:  "Codefolio",
			Style: style.Bold,
			Fg:    style.ColorMagenta,
		}),
		builtin.CreateText(ctx, builtin.TextProps{
			Text: self.model,
			Fg:   style.ColorWhite,
		}),
		builtin.CreateText(ctx, builtin.TextProps{
			Text:  self.workDir,
			Style: style.Dim,
			Fg:    style.ColorWhite,
		}))
}
