// Code generated by tui generate. DO NOT EDIT.
// Source: mainpanel.gsx

package components

import (
	tui "github.com/grindlemire/go-tui"
)

type MainPanelView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *MainPanelView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *MainPanelView) GetRoot() *tui.Element { return v.Root }

func (v *MainPanelView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *MainPanelView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *MainPanelView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *MainPanelView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*MainPanelView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*MainPanelView)(nil)

var _ tui.AppUnbinder = (*MainPanelView)(nil)

var _ tui.PropsUpdater = (*MainPanelView)(nil)

func MainPanel(children []*tui.Element) *MainPanelView {
	var view MainPanelView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithHeightPercent(100.00),
		tui.WithFlexGrow(1),
		tui.WithMargin(1),
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
	)
	for _, __child := range children {
		__tui_0.AddChild(__child)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = MainPanelView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
