// Code generated by tui generate. DO NOT EDIT.
// Source: messages.gsx

package components

import (
	tui "github.com/grindlemire/go-tui"
)

type MessagesView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *MessagesView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *MessagesView) GetRoot() *tui.Element { return v.Root }

func (v *MessagesView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *MessagesView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *MessagesView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *MessagesView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*MessagesView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*MessagesView)(nil)

var _ tui.AppUnbinder = (*MessagesView)(nil)

var _ tui.PropsUpdater = (*MessagesView)(nil)

func Messages() *MessagesView {
	var view MessagesView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithFlexGrow(1),
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithScrollable(tui.ScrollVertical),
	)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = MessagesView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
