// Code generated by tux compile. DO NOT EDIT.

package components

import (
	"github.com/cylixlee/tux/builtin"
	"github.com/cylixlee/tux/renderer"
	"github.com/cylixlee/tux/style"
)

func (self *Prompt) Render(ctx renderer.Context) *renderer.Element {
	return builtin.CreateColumn(ctx, builtin.ColumnProps{
		Key:     "bottom",
		Padding: 1,
		Gap:     1,
	},
		builtin.CreateTextarea(ctx, builtin.TextareaProps{
			Key:         "editor",
			State:       self.state,
			Placeholder: "Ask something...",
			MinHeight:   1,
			MaxHeight:   8,
			AutoFocus:   true,
			Fg:          style.ColorWhite,
			OnKey:       self.onKey,
		}),
		builtin.CreateText(ctx, builtin.TextProps{
			Text:  "Enter send | modified Enter newline | Esc cancel | Ctrl+Up/Down history | Ctrl+C clear/quit",
			Style: style.Dim,
			Fg:    style.ColorWhite,
		}))
}
