// Code generated by tux compile. DO NOT EDIT.

package components

import (
	"github.com/cylixlee/tux/builtin"
	"github.com/cylixlee/tux/renderer"
	"github.com/cylixlee/tux/style"
)

func (self *Sidebar) Render(ctx renderer.Context) *renderer.Element {
	return builtin.CreateColumn(ctx, builtin.ColumnProps{
		Key:   "sidebar-wrap",
		Width: 42,
		Gap:   0,
		Bg:    Theme.BackgroundPanel,
	},
		builtin.CreateColumn(ctx, builtin.ColumnProps{
			Key:          "sidebar-content",
			Flex:         1,
			PaddingTop:   1,
			PaddingLeft:  2,
			PaddingRight: 2,
			Gap:          0,
			Bg:           Theme.BackgroundPanel,
		},
			builtin.CreateText(ctx, builtin.TextProps{
				Text:  "Untitled session",
				Style: style.Bold,
				Fg:    Theme.Text,
				Bg:    Theme.BackgroundPanel,
			}),
			builtin.CreateText(ctx, builtin.TextProps{
				Text:  self.workDir,
				Style: style.Dim,
				Fg:    Theme.TextMuted,
				Bg:    Theme.BackgroundPanel,
			}),
			builtin.CreateText(ctx, builtin.TextProps{
				Bg: Theme.BackgroundPanel,
			}),
			builtin.CreateText(ctx, builtin.TextProps{
				Text:  "Context",
				Style: style.Bold,
				Fg:    Theme.Text,
				Bg:    Theme.BackgroundPanel,
			}),
			builtin.CreateText(ctx, builtin.TextProps{
				Text: self.ContextTokens(),
				Fg:   Theme.TextMuted,
				Bg:   Theme.BackgroundPanel,
			}),
			builtin.CreateText(ctx, builtin.TextProps{
				Text: self.ContextPercent(),
				Fg:   Theme.TextMuted,
				Bg:   Theme.BackgroundPanel,
			}),
			builtin.CreateText(ctx, builtin.TextProps{
				Text: self.ContextReserve(),
				Fg:   Theme.TextMuted,
				Bg:   Theme.BackgroundPanel,
			}),
			builtin.CreateText(ctx, builtin.TextProps{
				Bg: Theme.BackgroundPanel,
			}),
			builtin.CreateText(ctx, builtin.TextProps{
				Text:  "MCP",
				Style: style.Bold,
				Fg:    Theme.Text,
				Bg:    Theme.BackgroundPanel,
			}),
			builtin.CreateText(ctx, builtin.TextProps{
				Text: self.mcp.Label,
				Fg:   self.MCPColor(),
				Bg:   Theme.BackgroundPanel,
			})),
		builtin.CreateRow(ctx, builtin.RowProps{
			Key:          "sidebar-footer",
			PaddingLeft:  2,
			PaddingRight: 2,
			Bg:           Theme.BackgroundPanel,
		},
			builtin.CreateText(ctx, builtin.TextProps{
				Text:  "● Codefolio",
				Style: style.Dim,
				Fg:    Theme.TextMuted,
				Bg:    Theme.BackgroundPanel,
			})),
		builtin.CreateText(ctx, builtin.TextProps{
			Bg: Theme.BackgroundPanel,
		}))
}
