// Code generated by tux compile. DO NOT EDIT.

package components

import (
	"fmt"
	"github.com/cylixlee/tux/builtin"
	"github.com/cylixlee/tux/renderer"
	"github.com/cylixlee/tux/style"
)

func (self *Sidebar) Render(ctx renderer.Context) *renderer.Element {
	return builtin.CreateColumn(ctx, builtin.ColumnProps{
		Key:   "sidebar-wrap",
		Width: 28,
	},
		builtin.CreateBorder(ctx, builtin.BorderProps{
			Key:         "sidebar",
			Title:       " Session ",
			BorderType:  builtin.BorderSingle,
			BorderColor: style.ColorWhite,
		},
			builtin.CreateColumn(ctx, builtin.ColumnProps{
				Gap: 1,
			},
				builtin.CreateText(ctx, builtin.TextProps{
					Text:  "SESSION",
					Style: style.Bold,
					Fg:    style.ColorWhite,
				}),
				builtin.CreateText(ctx, builtin.TextProps{
					Text: fmt.Sprintf("Messages  %v", self.messages),
					Fg:   style.ColorWhite,
				}),
				builtin.CreateText(ctx, builtin.TextProps{
					Text: fmt.Sprintf("Input     %v", self.inputTokens),
					Fg:   style.ColorWhite,
				}),
				builtin.CreateText(ctx, builtin.TextProps{
					Text: fmt.Sprintf("Output    %v", self.outputTokens),
					Fg:   style.ColorWhite,
				}),
				builtin.CreateText(ctx, builtin.TextProps{
					Text: fmt.Sprintf("Status    %v", self.status),
					Fg:   style.ColorWhite,
				}))))
}
