// Code generated by tui generate. DO NOT EDIT.
// Source: sidebar.gsx

package components

import (
	tui "github.com/grindlemire/go-tui"
)

type SidebarView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *SidebarView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *SidebarView) GetRoot() *tui.Element { return v.Root }

func (v *SidebarView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *SidebarView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *SidebarView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *SidebarView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*SidebarView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*SidebarView)(nil)

var _ tui.AppUnbinder = (*SidebarView)(nil)

var _ tui.PropsUpdater = (*SidebarView)(nil)

func Sidebar() *SidebarView {
	var view SidebarView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithWidth(32),
		tui.WithBackground(tui.NewStyle().Background(tui.RGBColor(16, 16, 16))),
		tui.WithPadding(1),
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
	)
	__tui_1 := tui.New(
		tui.WithText("Sidebar"),
	)
	__tui_0.AddChild(__tui_1)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = SidebarView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
