# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  SOURCES:
    - yoga
  BUILD_DIR: "{{.TASKFILE_DIR}}/build"
  INSTALL_DIR: "{{.TASKFILE_DIR}}/install"

tasks:
  build:
    desc: Build vendored dependencies
    dir: "{{.TASKFILE_DIR}}"
    preconditions:
      - sh: command -v cmake > /dev/null
        msg: CMake must be installed to build vendored dependencies.
      - sh: command -v ninja > /dev/null
        msg: Ninja must be installed to build vendored dependencies.
    cmds:
      - mkdir build
      - mkdir install
      - for: { var: SOURCES }
        cmd: cmake -S "src/{{.ITEM}}" -B "{{.BUILD_DIR}}/{{.ITEM}}" -G Ninja -DCMAKE_INSTALL_PREFIX="{{.INSTALL_DIR}}"
      - for: { var: SOURCES }
        cmd: cmake --build "{{.BUILD_DIR}}/{{.ITEM}}" --target install
    silent: true
