// Code generated by tux compile. DO NOT EDIT.

package main

import (
	"github.com/cylixlee/tux/renderer"
	components "github.com/open-portfolios/codefolio/cmd/cli/components"
)

func (self *App) Render(ctx renderer.Context) *renderer.Element {
	return components.NewShell(ctx, components.ShellProps{},
		components.NewHeader(ctx, components.HeaderProps{
			Model:   self.controller.ModelName(),
			WorkDir: self.workDir,
		}),
		components.NewTranscript(ctx, components.TranscriptProps{
			Messages:         self.controller.Messages(),
			Viewport:         self.viewport,
			Frame:            self.spinner.Get(ctx),
			OnToggleThinking: self.controller.ToggleThinking,
			OnToggleTool:     self.controller.ToggleTool,
		}),
		components.NewSidebar(ctx, components.SidebarProps{
			Messages:     len(self.controller.Messages()),
			InputTokens:  self.controller.InputTokens(),
			OutputTokens: self.controller.OutputTokens(),
			Status:       self.controller.Status(),
		}),
		components.NewPrompt(ctx, components.PromptProps{
			State: self.editor,
			OnKey: self.handleEditorKey,
		}),
		components.NewAskDialog(ctx, components.AskDialogProps{
			Open:       self.askOpen,
			Ask:        self.controller.Ask(),
			OnMove:     self.moveAsk,
			OnConfirm:  self.confirmAsk,
			OnDefaults: self.respondDefaults,
		})).Render(ctx)
}
