// Code generated by tux compile. DO NOT EDIT.

package main

import (
	"github.com/cylixlee/tux/renderer"
	p1 "github.com/open-portfolios/codefolio/cmd/cli/components"
)

func (self *App) Render(ctx renderer.Context) *renderer.Element {
	return p1.NewShell(ctx, p1.ShellProps{},
		p1.NewTranscript(ctx, p1.TranscriptProps{
			Messages:         self.controller.Messages(),
			Viewport:         self.viewport,
			Frame:            self.spinner.Get(ctx),
			OnToggleThinking: self.controller.ToggleThinking,
			OnToggleTool:     self.controller.ToggleTool,
		}),
		p1.NewSidebar(ctx, p1.SidebarProps{
			WorkDir: self.workDir,
		}),
		p1.NewPrompt(ctx, p1.PromptProps{
			State:   self.editor,
			OnKey:   self.handleEditorKey,
			Model:   self.controller.ModelName(),
			WorkDir: self.workDir,
		}),
		p1.NewAskDialog(ctx, p1.AskDialogProps{
			Open:       self.askOpen,
			Ask:        self.controller.Ask(),
			OnMove:     self.moveAsk,
			OnConfirm:  self.confirmAsk,
			OnDefaults: self.respondDefaults,
		})).Render(ctx)
}
