// Code generated by tui generate. DO NOT EDIT.
// Source: hello.gsx

package main

import (
	tui "github.com/grindlemire/go-tui"
)

type hello struct{}

func Hello() *hello { return new(hello) }

func (h *hello) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.On(tui.KeyEscape, func(e tui.KeyEvent) { e.App().Stop() }),
	}
}

func (h *hello) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithHeightPercent(100.00),
		tui.WithWidthPercent(100.00),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithAlign(tui.AlignCenter),
		tui.WithGap(1),
	)
	__tui_1 := tui.New(
		tui.WithText("Hello, Go TUI!"),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText("Press Esc to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_2)

	return __tui_0
}

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*hello)(nil)
)
