// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/open-portfolios/codefolio/cmd/cli/tui"
	"github.com/open-portfolios/codefolio/internal/conf"
	"github.com/open-portfolios/codefolio/internal/infra"
	"github.com/open-portfolios/codefolio/internal/infra/llm"
	"github.com/open-portfolios/codefolio/internal/infra/session"
	"github.com/open-portfolios/codefolio/internal/infra/tools"
	"github.com/open-portfolios/codefolio/internal/infra/tools/askuser"
	"github.com/open-portfolios/codefolio/internal/svc"
	"github.com/open-portfolios/codefolio/internal/svc/prompt"
)

// Injectors from wire.go:

func InitModel(cfg *conf.Global, askUserCh chan askuser.Request) (*tui.Model, func(), error) {
	driver, err := llm.NewDriver(cfg)
	if err != nil {
		return nil, nil, err
	}
	executorFactory := infra.NewExecutorFactory()
	toolRegistry := tools.NewRegistry(askUserCh, cfg)
	promptService := prompt.NewPromptService()
	agent := svc.NewAgent(driver, executorFactory, toolRegistry, promptService)
	domainSession := session.New()
	environmentService := infra.NewEnvironmentService()
	model := tui.NewModel(cfg, agent, domainSession, promptService, environmentService, askUserCh)
	return model, func() {
	}, nil
}
